<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Fonts\iconfont.ttf" />
    <None Remove="Assets\Images\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="ScottPlot" Version="5.1.57" />
    <PackageReference Include="VirtualizingWrapPanel" Version="2.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CommunityToolkit.Mvvm">
      <HintPath>bin\Debug\net8.0-windows7.0\CommunityToolkit.Mvvm.dll</HintPath>
    </Reference>
    <Reference Include="DataConvertLib">
      <HintPath>bin\Debug\net8.0-windows7.0\DataConvertLib.dll</HintPath>
    </Reference>
    <Reference Include="HandyControl">
      <HintPath>bin\Debug\net8.0-windows7.0\HandyControl.dll</HintPath>
    </Reference>
    <Reference Include="HarfBuzzSharp">
      <HintPath>bin\Debug\net8.0-windows7.0\HarfBuzzSharp.dll</HintPath>
    </Reference>
    <Reference Include="MiniExcel">
      <HintPath>bin\Debug\net8.0-windows7.0\MiniExcel.dll</HintPath>
    </Reference>
    <Reference Include="ScottPlot">
      <HintPath>bin\Debug\net8.0-windows7.0\ScottPlot.dll</HintPath>
    </Reference>
    <Reference Include="SkiaSharp">
      <HintPath>bin\Debug\net8.0-windows7.0\SkiaSharp.dll</HintPath>
    </Reference>
    <Reference Include="SkiaSharp.HarfBuzz">
      <HintPath>bin\Debug\net8.0-windows7.0\SkiaSharp.HarfBuzz.dll</HintPath>
    </Reference>
    <Reference Include="UdpEx">
      <HintPath>bin\Debug\net8.0-windows7.0\UdpEx.dll</HintPath>
    </Reference>
    <Reference Include="VirtualizingWrapPanel">
      <HintPath>bin\Debug\net8.0-windows7.0\VirtualizingWrapPanel.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\iconfont.ttf" />
    <Resource Include="Assets\Images\logo.png" />
  </ItemGroup>

</Project>
